apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-service
  template:
    metadata:
      labels:
        app: front-end-service
    spec:
      containers:
      - name: front-end-service
        image: olegmarko7/front-end-service:1.0.1
        env:
          - name: BROKER_URL
            value: http://broker-service.info
        ports:
          - containerPort: 8081
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app: front-end-service
  ports:
    - protocol: TCP
      name: main-port
      port: 8081
      targetPort: 8081
      
